Rewrite navbar
realfagskjelleren/realfagskjelleren.no pull request #11
Opened 2022-02-06 16:39 UTC by MartinSkatvedt

Navbar now scales down to mobile and is responsive to most screens. It also utilises custom themes from chakra.

closes #10

2022-02-06 18:36 UTC, EvenAsl requested changes
Overall: very nice, good job!

There are a few remarks/comments that need to be fixed before merging.

2022-02-06 18:36 UTC, EvenAsl commented on client/.vscode/settings.json
> +    "editor.formatOnSave": true
Can we add this folder to `.gitignore`?

2022-02-06 18:36 UTC, EvenAsl commented on client/src/pages/_app.tsx
> +        <Component {...pageProps} />
This breaks urqlclient, rendering the backend useless.

How to fix: Instead of wrapping the entire app with Layout, wrap each page with Layout.

2022-02-06 18:36 UTC, EvenAsl commented on client/src/pages/index.tsx
> +  return <Box></Box>;
This change should not go through, se comment on `__app.tsx`

2022-02-06 18:36 UTC, EvenAsl commented on client/src/components/NavBar/MenuLinks.tsx
> +            <NavLink name="Login" url={MenuTypes.LOGIN} />
The type/"size of the letters" of the login and register links does not scale properly. 

Would also like some feedback such as "hover-underline" or similar.

2022-02-06 18:36 UTC, EvenAsl commented on client/src/components/NavBar/MenuToggle.tsx
> +      {isOpen ? <CloseIcon /> : <HamburgerIcon />}
Can we color the icons to black instead of white?

2022-02-06 20:06 UTC, MartinSkatvedt commented on client/.vscode/settings.json
> +    "editor.formatOnSave": true
Fixed, overlooked by me!

2022-02-06 20:07 UTC, MartinSkatvedt commented on client/src/components/NavBar/MenuLinks.tsx
> +            <NavLink name="Login" url={MenuTypes.LOGIN} />
Should scale better now, did some quick tests and seems to scale better.

2022-02-06 20:07 UTC, MartinSkatvedt commented on client/src/components/NavBar/MenuToggle.tsx
> +      {isOpen ? <CloseIcon /> : <HamburgerIcon />}
Fixed

2022-02-06 20:08 UTC, MartinSkatvedt commented on client/src/pages/_app.tsx
> +        <Component {...pageProps} />
Do we know why this breaks? I fixed it for the time beeing, but would be preferable to use it this way.

2022-02-07 09:29 UTC, EvenAsl commented on client/src/pages/_app.tsx
> +        <Component {...pageProps} />
To answer your question, there wasn't any specification of which endpoint to use for the component via urql, so it defaulted to localhost:3000/graphql via a 404. Therefore, e.g. the cookies generated from logging in or registering would not be assigned the browser. 

Regardless, I initially thought you _shouldn't_ warp the entire app with an urqlClient because we wanted to differentiate between server-side and non-server-side rendering. BUT it turn out that the various components overwrite each other so this is actually not a problem.

I'll fix this remark in a commit to the branch.

2022-02-07 09:35 UTC, EvenAsl commented on client/src/components/NavBar/MenuLinks.tsx
> +            <NavLink name="Login" url={MenuTypes.LOGIN} />
Great!

2022-02-07 09:44 UTC, EvenAsl approved these changes
Great this covers all the remarks I requested, and I looked into and added a commit to fix the urqlClient problems so we can now wrap our app with layout.

2022-02-07 09:52 UTC, merged